# Generated by Django 3.2.6 on 2022-08-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabuleiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JogadaX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n1', models.CharField(default='1', max_length=1)),
                ('n2', models.CharField(default='2', max_length=1)),
                ('n3', models.CharField(default='3', max_length=1)),
                ('n4', models.CharField(default='4', max_length=1)),
                ('n5', models.CharField(default='5', max_length=1)),
                ('n6', models.CharField(default='6', max_length=1)),
                ('n7', models.CharField(default='7', max_length=1)),
                ('n8', models.CharField(default='8', max_length=1)),
                ('n9', models.CharField(default='9', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='tabuleiro',
            name='numero',
        ),
    ]
