# Generated by Django 3.2.6 on 2022-08-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabuleiro', '0003_disabledx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disabledx',
            name='op1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='disabledx',
            name='op2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='disabledx',
            name='op3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='disabledx',
            name='op4',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='disabledx',
            name='op5',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='disabledx',
            name='op6',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='disabledx',
            name='op7',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='disabledx',
            name='op8',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='disabledx',
            name='op9',
            field=models.BooleanField(default=False),
        ),
    ]
