# Generated by Django 3.2.6 on 2022-08-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabuleiro', '0004_auto_20220829_1348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisabledX',
        ),
        migrations.DeleteModel(
            name='JogadaX',
        ),
        migrations.AddField(
            model_name='tabuleiro',
            name='jogada',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
    ]
