# Generated by Django 3.2.6 on 2022-08-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabuleiro', '0006_auto_20220830_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabuleiro',
            name='id_jogo',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
