# Generated by Django 3.2.6 on 2022-08-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabuleiro', '0007_tabuleiro_id_jogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_jogo', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
