# Generated by Django 3.2.6 on 2022-08-31 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabuleiro', '0009_auto_20220831_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogos',
            name='criado_em',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
