# Generated by Django 3.2.6 on 2022-08-31 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabuleiro', '0010_jogos_criado_em'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogos',
            name='id_jogo',
        ),
        migrations.AlterField(
            model_name='jogos',
            name='vencedor',
            field=models.CharField(default='Partida não finalizada', max_length=255),
        ),
    ]
